#' Surge Plot Data
#'
#' Generates a plot that shows the amount of people who were referred and treated, and referred but not treated, as
#' generated by the model.
#'
#' @param model_output output from \code{run_model()} and \code{get_model_output()}
#' @param column the column in `model_output` to calculate the summary for, either "group", "condition" or "treatment"
#'
#' @return a summarised version of \code{model_output}
#'
#' @importFrom dplyr %>% filter mutate across rename
surge_plot_data <- function(model_output, column) {
  model_output %>%
    filter(type != "new-at-risk") %>%
    surge_summary({{column}}) %>%
    mutate(across(.data$`new-referral`, ~.x - .data$`new-treatment`)) %>%
    rename("Received treatment" = .data$`new-treatment`,
           "Referred, but not treated" = .data$`new-referral`)
}

#' Surge Plot
#'
#' Generates a plot that shows the amount of people who were referred and treated, and referred but not treated, as
#' generated by the model.
#'
#' @param model_output output from \code{run_model()} and \code{get_model_output()}
#' @param column the column in `model_output` to calculate the summary for, either "group", "condition" or "treatment"
#'
#' @return a plotly chart
#'
#' @importFrom dplyr %>%
#' @importFrom plotly layout config add_trace
surge_plot <- function(model_output, column) {
  column <- enquo(column)
  df <- surge_plot_data(model_output, {{column}})

  if (nrow(df) < 1) return(NULL)

  plot_ly(df,
          x = ~`Received treatment`,
          y = ~group,
          text = paste0("<b>Received treatment</b><br>",
                        comma(df[["Received treatment"]])),
          hoverinfo = "text",
          type = "bar",
          name = "Received treatment") %>%
    add_trace(x = ~df[["Referred, but not treated"]],
              name = "Referred, but not treated",
              text = paste0("<b>Referred, but not treated</b><br>",
                            comma(df[["Referred, but not treated"]]))) %>%
    layout(xaxis = list(title = "Total Referrals / Treatments"),
           yaxis = list(title = ""),
           barmode = "stack",
           legend = list(xanchor = "right",
                         yanchor = "bottom",
                         x = 0.99,
                         y = 0.01)) %>%
    config(displayModeBar = FALSE)
}
