#' Referrals Plot
#'
#' Generates a plot that shows the referrals generated by the model.
#'
#' @param model_output output from \code{run_model()} and \code{get_model_output()}
#' @param treatment a name of a treatment to filter by
#'
#' @return a plotly chart
#'
#' @importFrom dplyr %>% filter group_by summarise across
#' @import rlang
#' @importFrom plotly plot_ly layout config
summarise_model_output <- function(model_output, type, treatment) {
  # thought that you should be able to call {{type}} and {{treatment}} in the filter call, but this seems to be causing
  # the results to not filter correctly.
  f_type <- type
  f_treatment <- treatment

  model_output %>%
    filter(.data$type == f_type,
           .data$treatment == f_treatment) %>%
    group_by(.data$date, .add = TRUE) %>%
    summarise(across(.data$value, sum), .groups = "drop_last")
}
