#' Referrals Plot
#'
#' Generates a plot that shows the referrals generated by the model.
#'
#' @param model_output output from \code{run_model()} and \code{get_model_output()}
#' @param treatment a name of a treatment to filter by
#'
#' @return \code{referrals_plot()}: a plotly chart
#'
#' @importFrom dplyr %>%
#' @importFrom plotly plot_ly layout config
referrals_plot <- function(model_output, treatment) {
  df <- referrals_plot_data(model_output, treatment)

  if (nrow(df) < 1) return(NULL)

  plot_ly(df,
          type = "scatter",
          mode = "lines",
          x = ~date,
          y = ~Referrals,
          name = "Referrals",
          text = ~comma(Referrals),
          hoverinfo = "text",
          hovertemplate = "%{text}",
          line = list(color = "#f8bf07")) %>%
    add_trace(y = ~Treatments,
              name = "Treatments",
              text = ~comma(Treatments),
              line = list(color = "#587FC1")) %>%
    layout(showlegend = FALSE,
           hovermode = "x unified",
           xaxis = list(title = "Month"),
           yaxis = list(title = "New Referrals/Treatments")) %>%
    config(displayModeBar = FALSE)
}

#' @rdname referrals_plot
#'
#' @return \code{referrals_plot_data()}: a summarised version of \code{model_output}
#'
#' @importFrom dplyr %>%
#' @importFrom purrr map_dfr
referrals_plot_data <- function(model_output, treatment) {
  c("Referrals" = "new-referral",
    "Treatments" = "new-treatment") %>%
    map_dfr(summarise_model_output,
            model_output = model_output,
            treatment = treatment,
            .id = "type") %>%
    pivot_wider(names_from = type, values_from = value)
}
