#' Referrals Plot
#'
#' Generates a plot that shows the referrals generated by the model.
#'
#' @param model_output output from \code{run_model()} and \code{get_model_output()}
#' @param treatment a name of a treatment to filter by
#'
#' @return \code{referrals_plot()}: a plotly chart
#'
#' @importFrom dplyr %>%
#' @importFrom plotly plot_ly layout config
referrals_plot <- function(model_output, treatment) {
  df <- referrals_plot_data(model_output, treatment)

  if (nrow(df) < 1) return(NULL)

  plot_ly(df,
          type = "scatter",
          mode = "lines",
          x = ~date,
          y = ~value,
          hovertext = NULL,
          hovertemplate = paste("<b>Month</b>: %{x}",
                                "<b>Referrals</b>: %{y:.0f}",
                                "<extra></extra>",
                                sep = "<br>")) %>%
    layout(showlegend = FALSE,
           xaxis = list(title = "Month"),
           yaxis = list(title = "New Referrals")) %>%
    config(displayModeBar = FALSE)
}

#' @rdname referrals_plot
#'
#' @return \code{referrals_plot_data()}: a summarised version of \code{model_output}
#'
#' @importFrom dplyr %>%
referrals_plot_data <- function(model_output, treatment) {
  model_output %>%
    summarise_model_output("new-referral", treatment)
}
