options(tidyverse.quiet = TRUE)

suppressPackageStartupMessages({
  library(magrittr)
  library(tidyverse)
  library(deSolve)
  library(patchwork)
  library(plotly, exclude = c("last_plot", "filter", "layout"))
  library(rlang)
  library(shiny)
  library(shinyWidgets)
  library(shinycssloaders)
  library(shinydashboard)
  library(jsonlite, exclude = c("flatten", "validate"))
  library(packcircles)
  library(lubridate, exclude = c("intersect", "setdiff", "union"))
  library(readxl)
  library(writexl)
  library(glue, exclude = "collapse")
  library(igraph, exclude = "compose")
})
